exclude: [".rvmrc", ".rbenv-version", ".gitignore", "README.md", "Rakefile", "changelog.md", "Gemfile", "Gemfile.lock", "Procfile", "vendor"]

# Name of your blog (this will show up at the top of your page and in the RSS feed)
name: Michael Lancaster

# Short description (goes below the title; it will also be used in the RSS feed)
description: Front End Developer/HTML5 Soldier

# Your name, as you want it to appear underneath each post and in the footer
author: Michael Lancaster

# The directory for category index pages. Change it to something else if
# for example you want links like /categories/category1 instead of /category1
category_dir: /

# Uncomment if you are planning to run the blog in a subdirectory
# Note - if you enable this, and attempt to view your site locally you have to use the baseurl in your local path.
# Example, you must use http://localhost:4000/path/to/blog
#baseurl: /path/to/blog 

# The URL of your actual domain. This will be used to make absolute links in the RSS feed.
url: http://bymichaellancaster.com/

# Continue compiling even if there are errors. Keep it true, unless troubleshooting.
auto: false

# Makes pretty (descriptive) permalinks. See Jekyll docs for alternatives.
# /blog/:year/:month/:day/:title
permalink: /blog/:title
